// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using TitanicWeather.Models;

#nullable disable

namespace TitanicWeather.TitanicContext
{
    public partial class TitanicdatabaseContext : DbContext
    {
        public TitanicdatabaseContext()
        {
        }

        public TitanicdatabaseContext(DbContextOptions<TitanicdatabaseContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Measurement> Measurements { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlServer(Secrets.SqlString);
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.Entity<Measurement>(entity =>
            {
                entity.Property(e => e.DateAndTime).HasColumnType("datetime");

                entity.Property(e => e.Humidity).HasColumnType("decimal(10, 1)");

                entity.Property(e => e.Pressure).HasColumnType("decimal(10, 1)");

                entity.Property(e => e.Temperature).HasColumnType("decimal(10, 1)");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}